server:
  port: 8888
  ver: 1.0
  servlet:
    context-path: /

web:
  description: 웹 관련 설정
  config:
    description: 페이지 당 기본 게시물 갯수
    default-page-size: 10
    max-page-size: 100  

datasource:
  defaultdb:
    platform: postgresql
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/test_db
    username: postgres
    password: sktysh12
    dbSettingTypeDescription: JNDI OR POOL
    dbSettingType: POOL
    jndi-name: java:comp/env/BIZ_JNDI
spring:
  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://127.0.0.1:5432/test_db
    username: postgres
    password: sktysh12
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  config: classpath:log4j2.xml